# terraform.tfvars
project_id                 = "video-smarts-develop"
region                     = "europe-west2"
cb_region                  = "europe-west2"
my_org                     = ""
service_name               = "video-intelligence"
repository_name            = "youtube-and-video"
repository_name_app        = "YV-app"
repository_owner           = "ayubaw"
artifact_repo_name         = "video-intelligence"
github_app_installation_id = "96391224"
log_level                  = "DEBUG"
github_pat_secret_id       = "github-pat"
trigger_branch_name        = "dev"